### ISSUE TITLE
Calendar dialog - wrong calendar account

### ISSUE THREAD

**Issue by himdel** [PSilling/rh-massages#149]
The button to add to calendar always leads to `https://calendar.google.com/calendar/r/eventedit`.

But, if you're using home & work profiles, most likely the work calendar URL is actually `https://calendar.google.com/calendar/b/1/r/eventedit` (=second profile).

We should make it possible to set a preferred calendar account number/url so that people using multiple google profiles can configure the right one.

**Comment by PSilling** [comment]
That is a valid point. I will probably add this to the Settings view.
